spring:
  freemarker:
    cache: 'false'
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'
  jackson:
    serialization:
      fail-on-empty-beans: 'false'

  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password: ''
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
