spring:
  freemarker:
    cache: 'false'
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'
  jackson:
    serialization:
      fail-on-empty-beans: 'false'

  datasource:
    username: admin
    url: jdbc:mysql://kakao-clone-database.czslwzgjkozy.ap-northeast-2.rds.amazonaws.com:3306/kakao_clone_database
    password: yuns980603
  jpa:
    hibernate:
      ddl-auto: update

# 아마존 s3
cloud:
  aws:
    s3:
      bucket: kang--bucket
    credentials:
      access-key: AKIA5ABRQ3IVOAOPZA6G
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR